// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int n = Integer.parseInt(args[0]);
		int above = 0, below = 0;
		for (int i = 0; i < n; i++) {
			double random = Math.random();
			if (random > 0.5) {
				above += 1;
			} else {
				below += 1;
			}
		}

		System.out.println("> 0.5: " + above + " times");
		System.out.println("<= 0.5: " + below + " times");

		if (below != 0 && above != 0) {
			double ratio = (double) above / below;
			System.out.printf("Ratio: %.15f%n", ratio);
		}

	}
}
